export const palette = {
  primary:         '#7B1A3A',
  primaryLight:    '#F5E8EE',
  secondary:       '#C2476A',
  success:         '#1E7A50',
  successLight:    '#E6F5EE',
  warning:         '#B86918',
  warningLight:    '#FFF3E0',
  danger:          '#B91C1C',
  dangerLight:     '#FEE2E2',
  surface:         '#FFFFFF',
  background:      '#FBF7F8',
  border:          '#EDD5DE',
  textPrimary:     '#1A0A12',
  textSecondary:   '#7B4A5C',
  textDisabled:    '#C4A0B0',
  skeleton:        '#EDDBDF',
  skeletonShimmer: '#F7EEF1',
} as const;
